name: brahma-kalasha
region: blr
services:
  - name: api
    environment_slug: node-js
    github:
      branch: main
      deploy_on_push: true
      repo: Chan-electro/Resturant-Booking-App
    source_dir: /
    build_command: npm run build
    run_command: node apps/api/dist/src/main.js
    http_port: 3001
    routes:
      - path: /api
    envs:
      - key: DATABASE_URL
        scope: RUN_AND_BUILD_TIME
        value: ${db.DATABASE_URL}
      - key: JWT_SECRET
        scope: RUN_TIME
        value: Vt/rxU3v09YjRT5mEqmaoy/n17jcDTVHzRJ+OXeGMA0=
      - key: JWT_REFRESH_SECRET
        scope: RUN_TIME
        value: dk/NC/xIA4MlAYWBkYYD0ryIuKwvWyXPzB4P+bQWY8U=
      - key: JWT_EXPIRES_IN
        scope: RUN_TIME
        value: 15m
      - key: JWT_REFRESH_EXPIRES_IN
        scope: RUN_TIME
        value: 7d
      - key: PORT
        scope: RUN_TIME
        value: "3001"
      - key: FRONTEND_URL
        scope: RUN_TIME
        value: ${web.PUBLIC_URL}

  - name: web
    environment_slug: node-js
    github:
      branch: main
      deploy_on_push: true
      repo: Chan-electro/Resturant-Booking-App
    source_dir: /
    build_command: npm run build
    run_command: npm run start --workspace=apps/web
    http_port: 3000
    routes:
      - path: /
    envs:
      - key: NEXT_PUBLIC_API_URL
        scope: RUN_AND_BUILD_TIME
        value: ${api.PUBLIC_URL}/api/v1
      - key: NEXTAUTH_URL
        scope: RUN_TIME
        value: ${web.PUBLIC_URL}
      - key: NEXTAUTH_SECRET
        scope: RUN_TIME
        value: nAGyh/ThXL5MFJLwUIJ5ePLG84UkQz5AKg/FtP9H2ao=

databases:
  - engine: PG
    name: db
    num_nodes: 1
    size: db-s-dev-database
    version: "15"
